FROM php:fpm-alpine

# # Install Python Dependencies
RUN apk add py3-pip
RUN pip install extract-msg
RUN adduser root www-data && chown -R www-data:www-data /var/www && chmod -R g+rwX /var/www
COPY entrypoint.sh /var/entrypoint.sh
RUN chmod 755 /var/entrypoint.sh
#  [/var/entrypoint.sh]
# CMD ["adduser root www-data && chown -R www-data:www-data /var/www && chmod -R g+rwX /var/www"] 
# ENTRYPOINT ["php-fpm"]
CMD ["php-fpm"]