version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    ports: 
      - "8081:80"
    networks:
      - internal
    volumes:
    - ./frontend/:/var/www/html/
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD : "${DB_PWD}"

  php:
    build:
      context: .
      dockerfile: dockerfile-php
    restart: unless-stopped
    networks:
      - internal
    volumes:
    - ./frontend/:/var/www/html/
networks:
  internal:
    driver: bridge