version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
    - /home/james/repos/msg-converter/web-app/nginx/frontend:/var/www/html
  php:
    image: php:fpm-alpine
    networks:
      - internal
    volumes:
    - /home/james/repos/msg-converter/web-app/nginx/frontend:/var/www/html
networks:
  internal:
    driver: bridge