version: "3"
services:

  nginx-msg-converter:
    image: nginx:alpine
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports: 
      - "8085:80"
      
  php-msg-converter:
    image: php:fpm-alpine
    build:
      context: .
      dockerfile: dockerfile-php
    restart: always
    depends_on:
      - nginx
