FROM php:fpm-alpine

# # Install Dependencies
RUN apk add py3-pip
RUN apk add coreutils
RUN pip install extract-msg

# Copy scripts into container
COPY scripts/entrypoint /usr/local/bin/entrypoint
COPY frontend/ /var/www/html/
COPY .env /usr/local/bin/.env

# Run Commands
RUN chmod 755 /usr/local/bin/entrypoint
RUN chmod u+x /usr/local/bin/entrypoint
CMD ["php-fpm"]