version: "3"
services:

  nginx:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports: 
      - "8081:80"
    networks:
      - internal


  db:
    image: mongo
    restart: unless-stopped
    ports: 
      - "8082:8081"
    networks:
      - internal
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${DB_PWD}"
      

  php:
    build:
      context: .
      dockerfile: dockerfile-php
    restart: always
    networks:
      - internal
      
networks:
  internal:
    driver: bridge