version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: dockerfile
    ports: 
      - "8081:80"
    networks:
      - internal
    volumes:
    - /home/james/container-program-files/msg-converter/web-app/nginx/frontend/:/var/www/html/
  php:
    build:
      context: .
      dockerfile: dockerfile-php
    image: php:fpm-alpine
    networks:
      - internal
    volumes:
    - /home/james/container-program-files/msg-converter/web-app/nginx/frontend/:/var/www/html/
networks:
  internal:
    driver: bridge