version: "3"
services:

  nginx:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports: 
      - "8081:80"
    networks:
      - internal

  mongodb:
    image: mongo
    restart: unless-stopped
    ports: 
      - "27017:27017"
    networks:
      - internal
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PWD}"
      MONG_INITDB_DATABASE: "db_1"
    depends_on:
      - php

  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - 8082:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: "${DB_PWD}"
  #     ME_CONFIG_MONGODB_URL: mongodb://root:$DB_PWD@mongodb:27017/db_1?authSource=admin
  #     ME_CONFIG_MONGODB_SERVER: mongodb
  #   depends_on:
  #     - mongodb

  php:
    build:
      context: .
      dockerfile: dockerfile-php
    restart: always
    networks:
      - internal
    depends_on:
      - nginx
      
networks:
  internal:
    driver: bridge